#include "si_provisioning.h"

#include "esphome/core/log.h"
#include "esphome/core/application.h"
#include "esphome/core/hal.h"
#include "esphome/components/wifi/wifi_component.h"
#include "esphome/components/mqtt/mqtt_client.h"
#include "esphome/components/json/json_util.h"

#include <WiFi.h>
#include <HTTPClient.h>
#include <WiFiClientSecure.h>
#include <ESPAsyncWebServer.h>
#include <DNSServer.h>
#include <esp_wifi.h>

// Forward-declared globals generated by ESPHome from the YAML `globals:` block.
namespace esphome {
extern globals::RestoringGlobalsComponent<std::string> *mqtt_user;
extern globals::RestoringGlobalsComponent<std::string> *mqtt_pass;
extern globals::RestoringGlobalsComponent<std::string> *mqtt_topic_prefix;
extern globals::RestoringGlobalsComponent<bool> *provisioned;
}  // namespace esphome

namespace esphome {
namespace si_provisioning {

static const char *const TAG = "si_provisioning";

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------
std::string SiProvisioning::mac_suffix_(uint8_t bytes) const {
  uint8_t mac[6];
  esp_read_mac(mac, ESP_MAC_WIFI_STA);
  char buf[13];
  if (bytes == 2) {
    snprintf(buf, sizeof(buf), "%02X%02X", mac[4], mac[5]);
  } else {
    snprintf(buf, sizeof(buf), "%02X%02X%02X", mac[3], mac[4], mac[5]);
  }
  return std::string(buf);
}

std::string SiProvisioning::ap_ssid_() const {
  return std::string("SI-") +
         (device_type_ == "pool" ? "Pool" : "Water") +
         "-Setup-" + this->mac_suffix_(2);
}

// -----------------------------------------------------------------------------
// Lifecycle
// -----------------------------------------------------------------------------
void SiProvisioning::setup() {
  ESP_LOGI(TAG, "si_provisioning ready (device_type=%s)", device_type_.c_str());
}

void SiProvisioning::boot_apply() {
  const bool is_provisioned = provisioned->value();
  ESP_LOGI(TAG, "boot_apply: provisioned=%s", is_provisioned ? "true" : "false");

  if (is_provisioned && !mqtt_user->value().empty()) {
    auto *c = mqtt::global_mqtt_client;
    c->set_username(mqtt_user->value().c_str());
    c->set_password(mqtt_pass->value().c_str());
    c->set_topic_prefix(mqtt_topic_prefix->value());
    ESP_LOGI(TAG, "Applied stored MQTT creds (user=%s, prefix=%s)",
             mqtt_user->value().c_str(),
             mqtt_topic_prefix->value().c_str());
    return;
  }

  // Not provisioned: keep MQTT idle (blank creds) and stand up the captive portal.
  this->start_provisioning_portal_();
}

void SiProvisioning::loop() {
  if (portal_active_ && dns_ != nullptr) {
    dns_->processNextRequest();
  }
}

// -----------------------------------------------------------------------------
// Captive portal (AP mode)
// -----------------------------------------------------------------------------
static const char PORTAL_HTML[] PROGMEM = R"HTML(
<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Solaire Intelligence Setup</title>
<style>
  body{font-family:-apple-system,sans-serif;max-width:420px;margin:2em auto;padding:0 1em;color:#222}
  h1{font-size:1.3em}label{display:block;margin-top:1em;font-weight:600}
  input{width:100%;padding:.6em;font-size:1em;border:1px solid #ccc;border-radius:6px;box-sizing:border-box}
  button{margin-top:1.5em;width:100%;padding:.8em;font-size:1em;background:#0a7;color:#fff;border:0;border-radius:6px}
</style></head><body>
<h1>Connect this device</h1>
<p>Enter your WiFi details and the registration code from your welcome email.</p>
<form method="POST" action="/provision">
  <label>WiFi network<input name="ssid" required maxlength="32"></label>
  <label>WiFi password<input name="password" type="password" maxlength="64"></label>
  <label>Registration code<input name="code" required maxlength="32" autocapitalize="characters"></label>
  <button type="submit">Connect</button>
</form>
</body></html>
)HTML";

void SiProvisioning::start_provisioning_portal_() {
  if (portal_active_) return;
  ESP_LOGW(TAG, "Starting provisioning AP: %s", this->ap_ssid_().c_str());

  WiFi.softAPdisconnect(false);
  WiFi.softAP(this->ap_ssid_().c_str(), "solairesetup");
  delay(100);

  IPAddress ap_ip = WiFi.softAPIP();
  dns_ = new DNSServer();
  dns_->setErrorReplyCode(DNSReplyCode::NoError);
  dns_->start(53, "*", ap_ip);

  server_ = new AsyncWebServer(80);
  auto serve_form = [](AsyncWebServerRequest *r) {
    r->send_P(200, "text/html", PORTAL_HTML);
  };
  server_->on("/", HTTP_GET, serve_form);
  server_->on("/generate_204", HTTP_GET, serve_form);     // Android
  server_->on("/hotspot-detect.html", HTTP_GET, serve_form);
