substitutions:
  logger_level: INFO

logger:
  level: ${logger_level}

api:

ota:
  platform: esphome

wifi:
  ap:

time:
  - platform: sntp
    id: sntp_time

web_server:
  port: 80

captive_portal:
