substitutions:
  logger_level: INFO
  public: true

esphome:
  name: si-gateway
  friendly_name: SI Gateway

packages:

  core:
    url: https://github.com/merv-gif/SI-gateway
    files:
      - packages/common.yaml
      - packages/esp32_rs485.yaml
    ref: main

  modbus:
    url: https://github.com/merv-gif/SI-gateway
    files:
      - path: packages/sunsynk_modbus.yaml
        vars:
          modbus_controller_id: inverter
          id_prefix: inverter_
          name_prefix: "Inverter "
    ref: main

modbus_controller:
  - id: inverter
    address: 0x01
    modbus_id: modbus_485
    setup_priority: -10
    update_interval: 15s
    command_throttle: 50ms
