substitutions:
  logger_level: INFO
  public: true

esphome:
  name: si-gateway-01
  friendly_name: SI Gateway

packages:
  common: !include ../packages/common.yaml
  device: !include ../packages/esp32_rs485.yaml
  modbus: !include
    file: ../packages/sunsynk_modbus.yaml
    vars:
      modbus_controller_id: inverter
      id_prefix: inverter_
      name_prefix: "Inverter "

modbus_controller:
  - id: inverter
    address: 0x01
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 15s
    command_throttle: 50ms
